name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write  # Add this to give write permission

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 8
      
      - uses: actions/setup-node@v4.2.0
        with:
          node-version: 20
          cache: 'pnpm'
      
      - run: pnpm install
      - run: pnpm run build
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          folder: build
          branch: gh-pages
          token: ${{ github.token }}  # Explicit token usage